name: release
on:
  workflow_dispatch:
    inputs:
      method:
        description: |
          Which number to increment in the semantic versioning.
          Set 'major', 'minor' or 'patch'.
        required: true
jobs:
  tag:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: kyoh86/git-vertag-action@v1.1
        with:
          method: ${{ github.event.inputs.method }}
          push: true
  golang:
    needs: tag
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      # サブディレクトリにGoのモジュールがあるため、サブディレクトリのパスを先頭に付けたTagを追加で発行する
      - name: go module version tag
        run: |
          TAG_VERSION=$(git describe --tags --abbrev=0 --match='v*.*.*')
          MODULE_VERSION=go/$TAG_VERSION
          git tag $MODULE_VERSION
          git push origin $MODULE_VERSION
  typescript:
    needs: tag
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: ts package version tag
        id: version
        run: |
          PACKAGE_VERSION=$(git describe --tags --abbrev=0 --match='v*.*.*' | sed -e 's/v//')
          echo "::set-output name=package_version::${PACKAGE_VERSION}"
      - name: bump version
        run: |
          jq '.version|="${{ steps.version.outputs.package_version }}"' ts/package.json > tmp
          mv tmp ts/package.json
      - name: commit package.json
        run: |
          [[ ! $(git diff --exit-code ts/package.json) ]] && echo "Nothing to commit." && exit 0
          git config user.name "gRPC Bot"
          git pull
          git add ts/package.json
          git commit -m "chore: bump version to ${{ steps.version.outputs.package_version }}"
          git push
      - uses: actions/setup-node@v2
        with:
          node-version: '14'
          registry-url: 'https://npm.pkg.github.com'
          scope: '@amothic'
      - run: npm publish
        working-directory: ./ts
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
